# Generated by Django 4.1.3 on 2022-12-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(upload_to='profiles/%Y/%m/'),
        ),
    ]
